function init_git_memo_list() {
    memoList.push(["WikiHow", "https://ko.wikihow.com/%EB%8C%80%EB%AC%B8", "", "게시판,it"]);
    memoList.push(["개드립", "https://www.dogdrip.net/", "", "유머,정보,게시판"]);
    memoList.push(["파이썬 코딩 도장", "https://dojang.io/course/view.php?id=7", "", "Python, coding"]);
    memoList.push(["미래를 만든 Geeks", "https://www.folklore.org/", "apple 매킨토시 역사", "Macintosh"]);
    memoList.push(["Refactoring Guru", "https://refactoring.guru/", "리팩토링, 디자인 패턴", "design pattern"]);
    memoList.push(["Javascript Info", "https://javascript.info/", "", "자바 스크립트"]);
    memoList.push(["2cpu", "https://www.2cpu.co.kr/", "", "it,게시판"]);
    memoList.push(["Doom world", "https://www.doomworld.com/", "", "game,doom,it,둠"]);
    memoList.push(["Doom wiki", "https://doomwiki.org/wiki/Entryway", "", "doom,둠,wiki"]);
    memoList.push(["파비앙 사이트", "https://fabiensanglard.net/", "", "doom,game engine,game"]);
    memoList.push(["Google document", "https://docs.google.com/document/u/0/", "", "document,google,word,워드"]);
    memoList.push(["Google Sheet", "https://docs.google.com/spreadsheets/u/0/", "", "sheet,google,시트"]);
    memoList.push(["Gdrive", "https://drive.google.com/drive/u/0/my-drive", "", "구글 드라이브,drive,hard,google,cloud"]);
    memoList.push(["닌텐도 북미 eshop", "https://www.nintendo.com/games/switch", "", "e shop, usa, nintendo, america"]);
    memoList.push(["닌텐도 eshop", "https://store.nintendo.co.kr/", "", "e shop, 한국, nintendo, korea"]);
    memoList.push(["구미시립중앙도서관", "https://lib.gumi.go.kr/", "", "도서관, 인동, 독서"]);
    memoList.push(["클하대학교", "https://clhauniv.org/", "", "clubhouse,클럽하우스,대학교"]);
    memoList.push(["구미 버스 정보", "http://m.bis.gumi.go.kr/main/main.do", "", "구미,Gumi,버스,노선"]);
    memoList.push(["버스 배차 시간표", "http://m.bis.gumi.go.kr/city_bus/city_time_service.do", "", "구미, gumi, 시간"]);
    memoList.push(["Tetris", "http://www.chobocho.com/game/tetris/tetris.html", "", "테트리스, block, game"]);
    memoList.push(["신한생명 운세", "https://www.shinhanlife.co.kr/hp/cdhg0130.do", "", "사주"]);
    memoList.push(["디벨로퍼웍스 코리아 dW Korea - IBM Developer", "https://developer.ibm.com/kr/", "", "ibm, 개발"]);
    memoList.push(["모던 JavaScript 튜토리얼", "https://ko.javascript.info/", "", "개발, javascript, 자바스크립트"]);
    memoList.push(["[유머] 제갈량", "https://m.clien.net/service/board/park/15129599?type=recommend", "", "유머, 제갈량, 클리앙"]);
    memoList.push(["부산 개발자 커뮤니티", "https://cafe.naver.com/itcommuinty", "", "카페, cafe"]);
    memoList.push(["GeeksForGeeks", "https://www.geeksforgeeks.org/", "", "자료구조, 알고리즘, Data structure, Algorithms"]);
    memoList.push(["HP Museum", "https://www.hpmuseum.org/", "", "HP IT 박물관"]);
    memoList.push(["UnderKG", "http://underkg.co.kr/", "", "IT, Mobile, 모바일 소식"]);
    memoList.push(["코딩 도장", "https://dojang.io/", "", "it, study, python, cpp"]);
    memoList.push(["Repl", "https://repl.it/~", "", "code, study, python, cpp, codig"]);
    memoList.push(["Naver game", "https://game.naver.com", "", "game,naver"]);
    memoList.push(["Trend Talk", "https://news.trendtalk.kr", "", "china, trend, it, mobile, wechat"]);
    memoList.push(["부산대 학생 커뮤니티", "https://mypnu.net/", "", "communite,게시판,pnu,busan"]);
    memoList.push(["맥심코리아", "https://www.maximkorea.net/", "", "maxim, 19, 잡지"]);
    memoList.push(["월간 HR Insight", "https://www.hrinsight.co.kr/", "", "HR, 인사, 잡지"]);
    memoList.push(["p5js", "https://editor.p5js.org/", "", "javascript,자바스크립트,온라인,에디터"]);
    memoList.push(["Leetcode", "https://leetcode.com/", "", "code,coding,test,certi"]);
    memoList.push(["프로그래머스", "https://programmers.co.kr/", "", "코딩, 써티, study"]);
    memoList.push(["Okky", "https://okky.kr/articles/community"]);
    memoList.push(["BBC Korean", "http://www.bbc.com/korean", "", "plain_style"]);
    memoList.push(["보배드림", "https://www.bobaedream.co.kr/"]);
    memoList.push(["오늘의 유머 베스트 게시판", "http://m.todayhumor.co.kr/list.php?table=bestofbest"]);
    memoList.push(["오늘의 유머", "http://m.todayhumor.co.kr/"]);
    memoList.push(["82cook", "https://www.82cook.com/entiz/enti.php?bn=15"]);
    memoList.push(["일 잘하는 법", "https://www.google.com/search?q=site%3Aclien.net+%EC%9D%BC%EC%9E%98%ED%95%98&rlz=1C1FKPE_koKR929KR929&sxsrf=ALeKk01qPcR4wDIo7QdUos329F6iiagZ0g%3A1626104295103&ei=52HsYNvbBZCE-Abg0pDoAw&oq=site%3Aclien.net+%EC%9D%BC%EC%9E%98%ED%95%98&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGAFQ4A9YnBlg0xtoAXAAeACAAWaIAYwDkgEDMi4ymAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=gws-wiz&ved=0ahUKEwib64HH7t3xAhUQAt4KHWApBD0Q4dUDCA4&uact=5"]);
    memoList.push(["구미 187번 배차 시간표", "http://m.bis.gumi.go.kr/city_bus/time_table.do?route_id=18730&brtId=187&remark=%EA%B5%AC%EB%AF%B8%EC%97%AD_%EC%9D%B8%EB%8F%99%EC%A0%95%EB%A5%98%EC%9E%A5_%EA%B5%AC%ED%8F%89%ED%9C%B4%EB%A8%BC%EC%8B%9C%EC%95%84_%EA%B5%AC%EB%AF%B8%EC%97%AD", "", "구미, gumi, 시간"]);
}

